name: Check, Build, Publish and GitHub Pages deploy

on:
    pull_request:
    push:
        branches:
            - main

permissions:
    contents: read
    pages: write
    id-token: write
    pull-requests: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Packages
              run: |
                  npm install
            - name: Lint check
              run: |
                  npm run lint
            - name: Test check
              run: |
                  npm run test
            - name: Build
              run: |
                  npm run bundle
            - name: Publish
              uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: public
